# Analyze DB Structure Workflow Configuration
name: analyze-db-structure
description: "노션 백로그 데이터베이스 구조 분석 → 에이전트용 가이드 문서 자동 생성"
author: "Rentre-Dev"

# Config source for module settings
config_source: "{project-root}/.bmad/rentre-dev/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
notion_integration: "{config_source}:notion_integration"

# Module paths
installed_path: "{project-root}/.bmad/rentre-dev/workflows/analyze-db-structure"
module_path: "{project-root}/.bmad/rentre-dev"

# Template for guide generation
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Output paths
guides_folder: "{module_path}/data/guides"
default_output_file: "{guides_folder}/backlog-guide-summary.md"

# Guide templates for each backlog type
guide_templates:
  summary: "{module_path}/templates/guide-summary-template.md"
  type_guide: "{module_path}/templates/guide-type-template.md"
  hierarchy: "{module_path}/templates/guide-hierarchy-template.md"

standalone: true

# Prerequisites
prerequisites:
  - notion_integration must be "auto" (Notion MCP required)
  - User must provide Notion database URL
