# Prepare Backlog Workflow Configuration
name: prepare-backlog
description: "백로그 분석 및 준비 - 상/하위/연결 백로그 종합 분석, 요구사항 구조화, 컨텍스트 수집, 저장"
author: "Rentre-Dev"

# Config source for module settings
config_source: "{project-root}/{bmad_folder}/rentre-dev/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
notion_integration: "{config_source}:notion_integration"

# Module paths
installed_path: "{project-root}/{bmad_folder}/rentre-dev/workflows/prepare-backlog"
module_path: "{project-root}/{bmad_folder}/rentre-dev"

# Guide files for backlog structure understanding
guides_folder: "{module_path}/data/guides"
hierarchy_guide: "{guides_folder}/hierarchy-map.md"
summary_guide: "{guides_folder}/backlog-guide-summary.md"

# Templates
backlog_template: "{module_path}/templates/backlog-item-template.md"

# Tasks
gather_context_task: "{module_path}/tasks/gather-context.md"

# Step-file architecture
workflow_md: "{installed_path}/workflow.md"
steps_folder: "{installed_path}/steps"

# Output paths
data_path: "{module_path}/data"
output_folder: "{data_path}/backlogs"

standalone: true

# Web bundle configuration
web_bundle:
  name: "prepare-backlog"
  description: "백로그 준비 - 상/하위/연결 분석, 요구사항 구조화, 컨텍스트 수집"
  author: "Rentre-Dev"
  workflow_md: "{bmad_folder}/rentre-dev/workflows/prepare-backlog/workflow.md"
  web_bundle_files:
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/workflow.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-01-input.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-01b-continue.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-02-context-analysis.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-03-requirements.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-04-additional-context.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-05-context-verify.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-06-save.md"
    - "{bmad_folder}/rentre-dev/workflows/prepare-backlog/steps/step-07-complete.md"

# Can be invoked from other workflows (e.g., decompose-backlog)
invocable: true
invocation_params:
  - backlog_source # 백로그 소스 (notion_url, direct_input, search)
  - backlog_content # 백로그 내용 (직접 전달 시)
  - skip_save # 저장 건너뛰기 (호출 워크플로우에서 저장할 경우)

# Return values when invoked
return_values:
  - backlog_id # 백로그 ID
  - backlog_info # 백로그 메타정보 (YAML)
  - requirements # 구조화된 요구사항 (REQ-XXX)
  - acceptance_criteria # 구조화된 수용기준 (AC-XXX)
  - context_notes # 수집된 컨텍스트 (피그마, 참조 문서 등)
  - context_score # 컨텍스트 충족도 점수 (0-100)
  - backlog_folder # 저장된 폴더 경로
