# Quick Execute Workflow Configuration
name: quick-execute
description: "간단한 단독 백로그 빠른 실행 - 분해 없이 바로 분석 후 작업 시작"
author: "Rentre-Dev"

# Config source for module settings
config_source: "{project-root}/.bmad/rentre-dev/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
notion_integration: "{config_source}:notion_integration"
code_analysis_depth: "{config_source}:code_analysis_depth"

# Module paths
installed_path: "{project-root}/.bmad/rentre-dev/workflows/quick-execute"
module_path: "{project-root}/.bmad/rentre-dev"

# Related workflows (invocable)
analyze_codebase_workflow: "{module_path}/workflows/analyze-codebase/workflow.yaml"

# Related tasks
gather_context_task: "{module_path}/tasks/gather-context.md"

# Templates
backlog_template: "{module_path}/templates/backlog-item-template.md"

# Guide files
guides_folder: "{module_path}/data/guides"

# This is an interactive workflow with step-file architecture
template: false
workflow_file: "{installed_path}/workflow.md"
first_step: "{installed_path}/steps/step-01-get-backlog.md"

# Legacy reference (archived)
# instructions: "{installed_path}/instructions.md"

# Output paths
data_path: "{module_path}/data"
backlogs_output: "{data_path}/backlogs"
tasks_output: "{data_path}/tasks"

standalone: true

# Complexity thresholds for "simple" backlog
complexity_thresholds:
  max_estimated_hours: 4 # 4시간 이하
  max_acceptance_criteria: 5 # 수용기준 5개 이하
  max_affected_files: 10 # 영향받는 파일 10개 이하
  warning_keywords: # 이 키워드 발견 시 경고
    - "대규모"
    - "리팩토링"
    - "마이그레이션"
    - "아키텍처"
    - "전체"
    - "시스템"

# Prerequisites
prerequisites:
  - Simple, standalone backlog (not requiring decomposition)
  - Can be completed in a single work session
