# Correct Course Workflow Configuration
name: correct-course
description: "백로그 진행 중 발생하는 변경사항, 방향 수정, 범위 조정 등을 체계적으로 관리"
author: "Rentre-Dev"
version: "1.0.0"

# Configuration Sources
config_source: "{project-root}/.bmad/rentre-dev/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
notion_integration: "{config_source}:notion_integration"
date: system-generated

# Path Definitions
installed_path: "{project-root}/.bmad/rentre-dev/workflows/correct-course"
module_path: "{project-root}/.bmad/rentre-dev"
data_path: "{module_path}/data/backlogs"

# Workflow Settings
template: false
workflow_file: "{installed_path}/workflow.md"
first_step: "{installed_path}/steps/step-01-init.md"
standalone: true
web_bundle: true

# Step Configuration
steps:
  - step-01-init
  - step-02-identify-change
  - step-03-load-context
  - step-04-analyze-impact
  - step-05-apply-changes
  - step-06-complete

# Memory Configuration
memory:
  type: sidecar-file
  location: "{data_path}/{backlog_id}/change-history.yaml"

# Change Types
change_types:
  - id: requirement_change
    label: "요구사항 변경"
    description: "기존 요구사항의 수정 또는 새 요구사항 추가"
  - id: subtask_add
    label: "서브태스크 추가"
    description: "새로운 서브태스크 생성"
  - id: subtask_modify
    label: "서브태스크 수정"
    description: "기존 서브태스크 내용 변경"
  - id: scope_change
    label: "범위 변경"
    description: "백로그 범위 확대 또는 축소"
  - id: risk_identified
    label: "리스크 식별"
    description: "새로운 리스크 발견 및 대응"
  - id: priority_change
    label: "우선순위 변경"
    description: "작업 우선순위 재조정"

# MCP Integrations
mcp_tools:
  required: []
  optional:
    - serena
    - context7
    - playwright
    - notionApi

# Features
features:
  change_history_tracking: true
  block_traceability: true
  notion_sync: conditional # based on notion_integration config
