# Worktree Setup - Git Worktree 초기 환경 설정
name: worktree-setup
description: "Git Worktree 병렬 작업을 위한 초기 환경 설정 - 공유 폴더 구조 생성 및 symlink 설정"
author: "Backlog Pilot"

config_source: "{project-root}/.bmad/backlog-pilot/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
worktree_enabled: "{config_source}:worktree_enabled"
worktree_path: "{config_source}:worktree_path"
shared_path: "{config_source}:shared_path"
guides_path: "{config_source}:guides_path"
analysis_cache_path: "{config_source}:analysis_cache_path"

installed_path: "{project-root}/.bmad/backlog-pilot/workflows/worktree-setup"
module_path: "{project-root}/.bmad/backlog-pilot"

template: false
instructions: "{installed_path}/instructions.md"

standalone: true
