# Create Worktree - 백로그/태스크용 새 Worktree 생성
name: create-worktree
description: "백로그 또는 태스크 작업을 위한 새 Git Worktree 생성 - 브랜치 생성, 공유 데이터 연결"
author: "Backlog Pilot"

config_source: "{project-root}/.bmad/backlog-pilot/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
worktree_enabled: "{config_source}:worktree_enabled"
worktree_path: "{config_source}:worktree_path"
worktree_branch_prefix: "{config_source}:worktree_branch_prefix"
worktree_base_branch: "{config_source}:worktree_base_branch"
shared_path: "{config_source}:shared_path"
guides_path: "{config_source}:guides_path"
analysis_cache_path: "{config_source}:analysis_cache_path"

installed_path: "{project-root}/.bmad/backlog-pilot/workflows/create-worktree"
module_path: "{project-root}/.bmad/backlog-pilot"

template: false
instructions: "{installed_path}/instructions.md"

standalone: true
