# Review Progress Workflow Configuration
name: review-progress
description: "진행 상황 리뷰 및 리포트 생성"
author: "Rentre-Dev"

config_source: "{project-root}/.bmad/rentre-dev/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
date: system-generated

installed_path: "{project-root}/.bmad/rentre-dev/workflows/review-progress"
module_path: "{project-root}/.bmad/rentre-dev"
data_path: "{module_path}/data/backlogs"
report_template: "{module_path}/templates/progress-report.md"

template: "{report_template}"
instructions: "{installed_path}/instructions.md"
default_output_file: "{module_path}/data/reports/progress-report-{{date}}.md"

standalone: true
